name: Terraform and Docker CI

on:
  push:
    branches:
      - main  # Adjust to your branch if needed

jobs:
  terraform-docker:
    name: Apply Terraform and Run Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0  # Adjust as needed

    - name: Terraform Init
      run: terraform init
      working-directory: ./web3

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./web3

    - name: Build Docker Image
      run: docker build -t mywebsite:latest .
      working-directory: ./web3

    - name: Stop Existing Containers
      run: |
        docker ps -q --filter "ancestor=mywebsite:latest" | xargs -r docker stop || true

    - name: Remove Existing Containers
      run: |
        docker ps -a -q --filter "ancestor=mywebsite:latest" | xargs -r docker rm || true

    - name: Run Docker Container
      run: docker run -d -p 8087:80 mywebsite:latest
      working-directory: ./web3
