name: Terraform and Docker CI

on:
  push:
    branches:
      - main

jobs:
  terraform-docker:
    name: Apply Terraform and Run Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./git/web3 # Replace with your directory

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./git/web3  # Replace with your directo

    - name: Build Docker Image
      run: docker build -t mywebsite:latest .

    - name: Run Docker Container
      run: docker run -d -p 8083:80 mywebsite:latest
